### ISSUE TITLE
추가 기능 반영

### ISSUE THREAD

**Issue by JAEHEE25** [Co-Drive/Driver-Server#108]
### 📎 개요
추가 기능 반영

### 📑 TODO
  - [x] 유효성 검사 추가
  - [x] 팔로잉 현황 로직 수정
  - [x] 그룹 멤버 수, 승인 수 로직 수정
